FROM mcr.microsoft.com/playwright/python:v1.50.0-noble

RUN mkdir -p /tests
COPY ./integration/requirements.txt /tests/requirements.txt
WORKDIR /tests
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["pytest",  "--capture=tee-sys", "--tracing", "off", "--junit-xml=/tests/results/test-results-all.xml", "-s", "-vv"]