FROM python:3.10

COPY ./requirements.txt /srv/proxy/requirements.txt
WORKDIR /srv/proxy

RUN pip install --no-cache-dir -r requirements.txt
COPY . /srv/proxy

# Ensure run.sh is executable
RUN chmod +x /srv/proxy/run.sh

ENTRYPOINT ./run.sh